/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Candidat } from '../../models/candidat';

export interface GetAllCandidats$Params {
}

export function getAllCandidats(http: HttpClient, rootUrl: string, params?: GetAllCandidats$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Candidat>>> {
  const rb = new RequestBuilder(rootUrl, getAllCandidats.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Candidat>>;
    })
  );
}

getAllCandidats.PATH = '/api/v1/candidats/all';
