/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Application {
  appliedAt?: string;
  id?: number;
  status?: 'Pending' | 'Accepted' | 'Rejected';
}
