/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Experience } from '../models/experience';
import { GrantedAuthority } from '../models/granted-authority';
import { Notification } from '../models/notification';
import { OffreEmploi } from '../models/offre-emploi';
import { Token } from '../models/token';
export interface Candidat {
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  accountname?: string;
  authorities?: Array<GrantedAuthority>;
  competences?: Array<string>;
  credentialsNonExpired?: boolean;
  cv?: string;
  email?: string;
  enabled?: boolean;
  experiences?: Array<Experience>;
  firstname?: string;
  id?: number;
  inscriptionDate?: string;
  lastname?: string;
  notifications?: Array<Notification>;
  offres?: Array<OffreEmploi>;
  password?: string;
  profileCompleted?: boolean;
  role?: 'ROLE_ADMIN' | 'ROLE_CANDIDAT' | 'ROLE_RECRUTEUR';
  tokens?: Array<Token>;
  username?: string;
}
