/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Candidat } from '../models/candidat';
export interface Experience {
  candidat?: Candidat;
  description?: string;
  duree?: string;
  id?: number;
  post?: string;
}
