/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FormationRecommendationDto {
  competence?: Array<string>;
  description?: string;
  id?: number;
  plateforme?: string;
  relevanceScore?: number;
  titre?: string;
}
