/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Competence } from '../models/competence';
export interface Formation {
  competences?: Array<Competence>;
  description?: string;
  id?: number;
  plateforme?: string;
  titre?: string;
}
