/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserEntity } from '../models/user-entity';
export interface Notification {
  dateCreation?: string;
  id?: number;
  message?: string;
  plateforme?: string;
  user?: UserEntity;
}
