/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserEntity } from '../models/user-entity';
export interface NotificationDto {
  message?: string;
  role?: 'ROLE_ADMIN' | 'ROLE_CANDIDAT' | 'ROLE_RECRUTEUR';
  title?: string;
  user?: UserEntity;
}
