/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OffreEmploiSearchDto {
  description?: string;
  experience?: number | null;
  id?: number;
  localisation?: string;
  salaire?: number | null;
  titre?: string;
}
