/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Candidat } from '../models/candidat';
import { Recruteur } from '../models/recruteur';
export interface OffreEmploi {
  candidats?: Array<Candidat>;
  competences?: Array<string>;
  description?: string;
  experience?: number;
  id?: number;
  localisation?: string;
  recruteur?: Recruteur;
  salaire?: number;
  titre?: string;
}
