/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Application } from '../models/application';
import { Competence } from '../models/competence';
import { Recruteur } from '../models/recruteur';
export interface OffreEmploi {
  applications?: Array<Application>;
  competences?: Array<Competence>;
  description?: string;
  experience?: number;
  id?: number;
  localisation?: string;
  recruteur?: Recruteur;
  salaire?: number;
  status?: 'OPEN' | 'CLOSED';
  titre?: string;
}
