/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OffreRecommendationDto {
  combinedScore?: number;
  description?: string;
  id?: number;
  titre?: string;
}
