/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Experience } from '../models/experience';
export interface ProfilCandidatDto {
  competences?: Array<string>;
  cv?: string;
  email?: string;
  experiences?: Array<Experience>;
}
