/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserEntity } from '../models/user-entity';
export interface Token {
  expired?: boolean;
  id?: number;
  revoked?: boolean;
  token?: string;
  tokenType?: 'BEARER';
  user?: UserEntity;
}
