/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDetailsDto {
  accountname?: string;
  email?: string;
  firstname?: string;
  id?: number;
  lastname?: string;
  role?: 'ROLE_ADMIN' | 'ROLE_CANDIDAT' | 'ROLE_RECRUTEUR';
}
