/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FormationRecommendationDto } from '../../models/formation-recommendation-dto';

export interface GetFormationRecommendations$Params {
  candidatId: number;
}

export function getFormationRecommendations(http: HttpClient, rootUrl: string, params: GetFormationRecommendations$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FormationRecommendationDto>>> {
  const rb = new RequestBuilder(rootUrl, getFormationRecommendations.PATH, 'get');
  if (params) {
    rb.path('candidatId', params.candidatId, {});
  }
  rb.header('Authorization', `Bearer ${localStorage.getItem('token')}`);
  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FormationRecommendationDto>>;
    })
  );
}

getFormationRecommendations.PATH = '/api/v1/recommendations/formations/{candidatId}';
