/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { CandidatControllerService } from './services/candidat-controller.service';
import { FormationControllerService } from './services/formation-controller.service';
import { ProfilControllerService } from './services/profil-controller.service';
import { OffreEmploiControllerService } from './services/offre-emploi-controller.service';
import { NotificationControllerService } from './services/notification-controller.service';
import { AuthControllerService } from './services/auth-controller.service';
import { AdministrateurControllerService } from './services/administrateur-controller.service';
import { ApplicationControllerService } from './services/application-controller.service';
import { UtilisateurControllerService } from './services/utilisateur-controller.service';
import { RecommendationControllerService } from './services/recommendation-controller.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    CandidatControllerService,
    FormationControllerService,
    ProfilControllerService,
    OffreEmploiControllerService,
    NotificationControllerService,
    AuthControllerService,
    AdministrateurControllerService,
    ApplicationControllerService,
    UtilisateurControllerService,
    RecommendationControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
