/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface CompleteProfileCandidat$Params {
      body: string
}

export function completeProfileCandidat(http: HttpClient, rootUrl: string, params: CompleteProfileCandidat$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, completeProfileCandidat.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }


  rb.header('Authorization', `Bearer ${localStorage.getItem('token')}`);

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

completeProfileCandidat.PATH = '/api/v1/profile/candidat/completeProfile';
