/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OffreEmploi } from '../../models/offre-emploi';

export interface GetOffreById$Params {
  id: number;
}

export function getOffreById(http: HttpClient, rootUrl: string, params: {
  id: string | null
}, context?: HttpContext | undefined): Observable<StrictHttpResponse<OffreEmploi>> {
  const rb = new RequestBuilder(rootUrl, getOffreById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }
  rb.header('Authorization', `Bearer ${localStorage.getItem('token')}`);
  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OffreEmploi>;
    })
  );
}

getOffreById.PATH = '/api/v1/offres/trouverOffre/{id}';
