/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OffreEmploi } from '../../models/offre-emploi';
import {OffreEmploiDto} from "../../models/offre-emploi-dto";

export interface GetAllOffres$Params {
}

export function getAllOffres(http: HttpClient, rootUrl: string, params?: GetAllOffres$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OffreEmploiDto>>> {
  const rb = new RequestBuilder(rootUrl, getAllOffres.PATH, 'get');
  if (params) {
  }
  rb.header('Authorization', `Bearer ${localStorage.getItem('token')}`);
  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OffreEmploiDto>>;
    })
  );
}

getAllOffres.PATH = '/api/v1/offres/allOffres';
